# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('description', models.CharField(db_column='short_description', max_length=500, null=True)),
                ('opening_hours', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=8, null=True)),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('latitude', models.CharField(max_length=15, null=True)),
                ('longitude', models.CharField(max_length=15, null=True)),
                ('rating', models.IntegerField()),
                ('url', models.CharField(max_length=500, null=True)),
                ('imgUrl', models.CharField(db_column='imgurl', max_length=200, null=True)),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
    ]
