# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='description',
            field=models.CharField(db_column='short_description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='opening_hours',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
