# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_auto_20161210_1452'),
        ('discovery', '0002_auto_20161210_1732'),
    ]

    operations = [
    ]
