# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_merge_20161212_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='distance_ray',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='opening_hours',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
