# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0006_auto_20161216_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='distance_ray',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
