"""
Django settings for discovery_backend project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import json

VCAP_SERVICES = json.loads(os.environ['VCAP_SERVICES'])
"""
try:
    VCAP_SERVICES = json.loads(os.environ['VCAP_SERVICES'])
except:
    with open('VCAP_SERVICES.json') as vcap_services:
        VCAP_SERVICES = json.load(vcap_services)
"""
PRODUCTION = False if os.getenv('PRODUCTION') is None else True 

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 't=vjh3lw0w126seh6*#i3oyj9d8szx*h+!^iimmf@4)hrokrls'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'django-test.eu-gb.mybluemix.net',
    '127.0.0.1'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'django_auth0',
    'discovery',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# AUTHENTICATION_BACKENDS = [
#     'django_auth0.auth_backend.Auth0Backend'
# ]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'discovery_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_auth0.context_processors.auth0'
            ],
        },
    },
]

WSGI_APPLICATION = 'discovery_backend.wsgi.application'

# Auth0
AUTH0_CLIENT_ID = '17HF8EMG7YfYWutyzQWOqQuE1us77Qp2'
AUTH0_SECRET = 'DvbXjQVp1U52EXPE_ks4YUo9B9sZYyoluw3o73Zsn6F-XaDuZf1ShyOOLquiJ75P'

AUTH0_DOMAIN = 'discovery.eu.auth0.com'
AUTH0_CALLBACK_URL = 'https://django-test.eu-gb.mybluemix.net/auth/callback/'
AUTH0_SUCCESS_URL = '/'

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "../../static")
